different:
  runname:
  - beamsearch
  - slow_greedysearch
  - sampling
  topk:
  - 3
  - 1
  - 3
different_flags:
  sample_decoding:
  - false
  - false
  - true
  fast_predict:
  - false
  - false
  - false
memory: 22800
minutes: 1000
same:
  batchsize: 32
  modelname: "../model_save/../model_save/scotus_opinions/scotus opinions bart/_2nghuohb/epoch_0_steps_24266"
  tags: 'latency_test_v10'
  samples: '1000'
same_flags:
  - notraining
