different:
  runname:
  - beamsearch_top3
  - without_generate_greedysearch_top1
  - sampling_top3
  topk:
  - 3
  - 1
  - 3
different_flags:
  sample_decoding:
  - false
  - false
  - true
memory: 22800
minutes: 1000
same:
  notraining: ''
  samples: '1000'
  topk: '3'
same_flags: []
  # - debug
  # - no_training