different:
  runname:
  - b1
  - b8
  - b32
  - b64
  eval_batchsize:
  - 1
  - 8
  - 32
  - 64
different_flags: {}
memory: 22800
minutes: 100
same:
  batchsize: 8
  modelname: "t5-base"
  tags: 'latency_test_v11'
  samples: '1000'
same_flags:
  - notraining
